### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by jennydaman** [sondr3/dev-serve#2]
Hi there,

I am liking and using dev-serve as an alternative to [live-server](https://github.com/tapio/live-server), which seems abandoned.

Could you provide pre-compiled binaries for dev-serve? I suggest:

- https://github.com/cargo-bins/cargo-binstall
- https://opensource.axo.dev/cargo-dist/

**Comment by sondr3** [comment]
I already build and publish binaries for macOS/Linux/Windows in the [releases](https://github.com/sondr3/dev-serve/releases) tab and in a [homebrew tap](https://github.com/sondr3/homebrew-taps/). I tested with `cargo binstall` and it downloaded and installed the correct binary automatically. Let me know if you need some other mechanism to download binaries 😃
